version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: louvor_lagoinha_postgres
    environment:
      POSTGRES_DB: louvor_lagoinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
